apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentia-mapreduce
  namespace: sentia
  labels:
    app: sentia-mapreduce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentia-mapreduce
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sentia-mapreduce
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: pulluser
      containers:
      - image: localhost:5000/sentia/sentia-mapreduce:latest
        name: sentia-mapreduce
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /app/app/settings/settings.yml
            name: settings
            readOnly: true
            subPath: settings.yml
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 8
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: TZ
          value: "Asia/Shanghai"
        resources:
          limits:
            cpu: 1000m
            memory: 4096Mi
          requests:
            cpu: 10m
            memory: 1000Mi
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: settings.yml
                path: settings.yml
            name: env-cm-mapreduce
          name: settings
